name: wpt

on:
  push:
  pull_request:

jobs:
  wpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
      
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Run WPT
        run: |
          sudo $(which deno) run -A --unstable ./wpt/wpt.ts setup 
          deno run -A --unstable ./wpt/wpt.ts run -- eventsource/
